  name: my_messenger_app
  description: "A new Flutter project."
  publish_to: 'none'

  version: 2.6.1+1

  environment:
    sdk: ^3.10.8

  dependencies:
    flutter:
      sdk: flutter

    cupertino_icons: ^1.0.8
    socket_io_client: ^3.1.4
    image_picker: ^1.2.1
    http: ^1.6.0
    shorebird_code_push: ^2.0.5
    firebase_core: ^4.4.0
    firebase_messaging: ^16.1.1
    shared_preferences: ^2.5.4
    vibration: ^3.1.6
    record: ^6.2.0
    audioplayers: ^6.5.1
    path_provider: ^2.1.1
    permission_handler: ^12.0.1
    cloud_firestore: ^6.1.2
    audio_waveforms: ^2.0.2
    just_audio: ^0.9.43
    flutter_dotenv: ^5.1.0
    dio: ^5.4.0
    
    



  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^6.0.0
    msix: ^3.6.3

  flutter:
    uses-material-design: true
    assets:
      - shorebird.yaml
      - .env
